version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
    - checkout
    - run:
        name: commitlint
        command: make commitlint
    - run:
        name: self-include
        command: make self-include
    - run:
        name: build
        commitlint: make build
