name: CI

on: [push]

jobs:
  pipeline:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - run: |
        git fetch --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
    - name: self-include
      run: make self-include
    - name: build
      run: make build
    - name: push
      run: make push
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
